name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
template: |
  # What's Changed
  $CHANGES
  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

version-resolver:
  major:
    labels:
      - 'type: major'
  minor:
    labels:
      - 'type: minor'
  patch:
    labels:
      - 'type: fix'
      - 'type: maintenance'
      - 'type: docs'
